apiVersion: v1
kind: ReplicationController
metadata:
  name: flasktest
  labels:
    name: flasktest
    app: flasktest
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: flasktest
    spec:
      containers:
      - name: flasktest 
        # image: tsungchh/flasktest
        image: tsungchh/flasktest2:1
        ports:
        # - containerPort: 8000
        - containerPort: 8000