apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flasktest
  labels:
    name: flasktest
    app: flasktest
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: flasktest
    spec:
      containers:
      - name: flasktest 
        # image: tsungchh/flasktest
        image: tsungchh/foodiesvc:latest
        ports:
        # - containerPort: 8000
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: flasktest
  labels:
    name: flasktest
    app: flasktest
spec:
  selector:
    name: flasktest
  type: NodePort
  ports:
   - name: http
     port: 8000
     targetPort: 8000
     nodePort: 31000
     protocol: TCP