apiVersion: v1
kind: Service
metadata:
  name: flasktest
  labels:
    name: flasktest
    app: flasktest
spec:
  selector:
    name: flasktest
  type: NodePort
  ports:
   - name: http
     port: 8000
     targetPort: 8000
     nodePort: 30000
     protocol: TCP