---
- name: copy app yml files
  copy: 
    src: "{{item}}"
    dest: "/tmp/{{item}}"
  with_items: "{{ apps }}"

- name: stop all application
  environment: 
    KUBECONFIG: /etc/kubernetes/admin.conf
  ignore_errors: yes
  command: /usr/bin/kubectl delete -f "/tmp/{{item}}"
  when: APP is not defined 
  with_items: "{{ apps }}"

- name: stop application
  environment: 
    KUBECONFIG: /etc/kubernetes/admin.conf
  ignore_errors: yes
  command: /usr/bin/kubectl delete -f "/tmp/{{APP}}"
  when: APP is defined 

- name: bring up all application
  environment:  
    KUBECONFIG: /etc/kubernetes/admin.conf
  command: /usr/bin/kubectl create -f "/tmp/{{item}}"
  with_items: "{{ apps }}"
  when: APP is not defined 

- name: bring application
  environment: 
    KUBECONFIG: /etc/kubernetes/admin.conf
  command: /usr/bin/kubectl create -f "/tmp/{{APP}}"
  when: APP is defined 

    