---

- name: Add apt key
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present

- name: Add kubernetes apt repo
  apt_repository:
    repo: 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
    state: present

- name: Install essential packages
  apt: 
    name='{{item}}'
    state=present
    update_cache=yes
  with_items:
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni
    - docker.io


- name: Start docker
  systemd: name=docker state=started enabled=yes

- name: Start kubelet
  systemd: name=kubelet state=started enabled=yes